name: TFGuilds
version: ${project.version}
main: me.totalfreedom.tfguilds.TFGuilds
api-version: 1.16
authors: [ Fleek, super, speed ]
description: A guilds plugin for the TotalFreedom server.
softdepend:
  - TotalFreedomMod
commands:
  guild:
    description: A command to manage guilds
    usage: /<command> help
    aliases: [ g ]
  tfguilds:
    description: An information of TFGuilds plugin
    usage: /<command> [reload]
    aliases: [ tfg ]
  guildchatspy:
    description: Spy on guild chat
    usage: /<command>
    aliases: [ gchatspy, gcs ]
