name: TFGuilds
version: ${project.version}
main: totalfreedom.tfguilds.TFGuilds
api-version: 1.13
authors: [speednt]
description: Plugin which allows for players to make their own guilds on the server
commands:
  tfguilds:
    description: Plugin info
    usage: /<command>
    aliases: [guilds, tfguildsinfo, tfginfo, guildsinfo]
  createguild:
    description: Creates a guild
    usage: /<command> <name>
    aliases: [guildcreate]
  guildtag:
    description: Modify your guild's tag
    usage: /<command> <set <tag> | clear>
    aliases: [gtag]
  guildchat:
    description: Speak to your guild
    usage: /<command> <message>
    aliases: [gchat]