name: TFGuilds
version: ${project.version}
main: me.totalfreedom.tfguilds.TFGuilds
api-version: 1.15
authors: [speednt]
description: Plugin which allows for players to make their own guilds on the server
depend: [TotalFreedomMod, Aero]
commands:
  tfguilds:
    description: Plugin info
    usage: /<command> <reload>
    aliases: [guilds, tfguildsinfo, tfginfo, guildsinfo]
  createguild:
    description: Creates a guild
    usage: /<command> <name>
    aliases: [guildcreate]
  guildtag:
    description: Modify your guild's tag
    usage: /<command> <set <tag> | clear>
    aliases: [gtag]
  guildchat:
    description: Speak to your guild
    usage: /<command> <message>
    aliases: [gchat]
  disbandguild:
    description: Deletes your guild
    usage: /<command>
    aliases: [deleteguild]
  guildteleport:
    description: Teleport to other guild members
    usage: /<command> <player>
    aliases: [guildtp, tpguild]
  inviteguild:
    description: If invited, allows you to join a guild
    usage: /<command> <player>
    aliases: [guildinvite]
  leaveguild:
    description: Leave your guild
    usage: /<command>
    aliases: [guildleave]